dedotdev/dedot

packages/chaintypes/src/kusama/rpc.ts, packages/chaintypes/src/polkadot/rpc.ts, packages/chaintypes/src/substrate/rpc.ts, packages/codecs/src/known/runtime/EncodedVersionedFinalityProof.ts, packages/codecs/src/known/runtime/VersionedFinalityProof.ts, packages/codecs/src/known/runtime/index.ts, packages/specs/src/rpc/babe.ts, packages/specs/src/rpc/beefy.ts, packages/specs/src/rpc/index.ts, packages/types/src/babe.ts, packages/types/src/index.ts, packages/utils/src/string.ts
This PR addresses the issue as the title said.
=> Add specs for babe & beefy modules

packages/chaintypes/src/astar/rpc.ts, packages/chaintypes/src/kusama/rpc.ts, packages/chaintypes/src/moonbeam/rpc.ts, packages/chaintypes/src/polkadot/rpc.ts, packages/chaintypes/src/substrate/rpc.ts, packages/specs/src/rpc/index.ts, packages/specs/src/rpc/offchain.ts, packages/types/src/index.ts, packages/types/src/offchain.ts
This PR addresses the issue as the title said.
=> Add offchain RPC specs

packages/chaintypes/src/kusama/rpc.ts, packages/chaintypes/src/polkadot/rpc.ts, packages/chaintypes/src/substrate/rpc.ts, packages/specs/src/rpc/index.ts, packages/specs/src/rpc/mmr.ts, packages/types/src/index.ts, packages/types/src/mmr.ts
This PR addresses the issue as the title said.
=> Add specs for mmr module

packages/api/src/client/Dedot.ts, packages/api/src/types.ts, packages/utils/package.json, packages/utils/src/event/EventEmitter.ts, packages/utils/src/event/index.ts, packages/utils/src/index.ts, yarn.lock
This will emit provider events, helpful when we want to track connection status in dapp or wallet.
=> feat(api): emit provider events

packages/api/src/client/BaseSubstrateClient.ts, packages/api/src/client/Dedot.ts, packages/api/src/client/__tests__/Dedot.spec.ts, packages/api/src/client/__tests__/MockProvider.ts, packages/api/src/types.ts
Adding a base abstraction for a substrate client, preparing for a new client based on json-rpc-v2.
=> feat: base abstraction for substrate client

packages/api/src/json-rpc/JsonRpcClient.ts, packages/providers/package.json, packages/providers/src/SubscriptionProvider.ts, packages/providers/src/base/SubscriptionProvider.ts, packages/providers/src/base/index.ts, packages/providers/src/index.ts, packages/providers/src/smoldot/SmoldotProvider.ts, packages/providers/src/smoldot/index.ts, packages/providers/src/ws/WsProvider.ts, yarn.lock
=> feat(providers): add `SmoldotProvider`

packages/api/src/json-rpc/group/ChainHead/BlockUsage.ts, packages/api/src/json-rpc/group/ChainHead/ChainHead.ts, packages/api/src/json-rpc/group/ChainHead/error.ts, packages/api/src/json-rpc/group/__tests__/ChainHead.spec.ts, packages/api/src/json-rpc/group/__tests__/simulator.ts
I'm not super happy with this setup right now, but let's merge this now and refactor this whole thing altogether later.
=> fix(api): improve unpin strategy

.github/workflows/zombienet-tests.yml, examples/dapp/package.json, package.json, packages/api/package.json, packages/api/src/extrinsic/extensions/known/StorageWeightReclaim.ts, packages/api/src/extrinsic/extensions/known/index.ts, packages/cli/package.json, packages/codegen/package.json, packages/providers/package.json, packages/utils/package.json, yarn.lock, zombienet-tests/src/0001-verify-chain-head-logic.ts
=> chore: bump deps versions & zombienet executables versions

packages/shape/package.json, packages/shape/src/deshape.ts, packages/shape/src/extension/alias.ts, packages/shape/src/extension/array.ts, packages/shape/src/extension/compact.ts, packages/shape/src/extension/createShape.ts, packages/shape/src/extension/hex.ts, packages/shape/src/extension/index.ts, packages/shape/src/extension/object.ts, packages/shape/src/extension/option.ts, packages/shape/src/extension/raw.ts, packages/shape/src/extension/result.ts, packages/shape/src/extension/str.ts, packages/shape/src/index.ts, packages/shape/src/lean/Enum.ts, packages/shape/src/lean/Struct.ts, yarn.lock
=> fix(shape): subshape -> deshape

packages/api/src/chaintypes/substrate/tx.ts, packages/api/src/extrinsic/submittable/SubmittableExtrinsic.ts, packages/api/src/extrinsic/submittable/SubmittableExtrinsicV2.ts, packages/api/src/extrinsic/submittable/utils.ts, packages/codecs/src/codecs/extrinsic/__tests__/Extrinsic.spec.ts, packages/codegen/src/chaintypes/generator/TxGen.ts, packages/types/src/extrinsic.ts, zombienet-tests/src/0001-check-tx-batch.ts, zombienet-tests/src/0001-check-tx-transfer-balance.ts
=> breaking: merge tx status

packages/api/src/extrinsic/submittable/BaseSubmittableExtrinsic.ts, yarn.lock, zombienet-tests/package.json, zombienet-tests/src/0001-check-tx-alter-payload.ts, zombienet-tests/src/0001-small-network.zndsl
=> feat: allow signer to alter the payload

packages/api/src/extrinsic/submittable/BaseSubmittableExtrinsic.ts, zombienet-tests/src/0001-check-tx-alter-payload.ts, zombienet-tests/src/0001-small-network.zndsl
Regression of #160 
This fix make sure the tx signature is presence for altered tx from signer
=> fix: ensure signature presence for altered tx

packages/api/src/client/DedotClient.ts, packages/api/src/client/LegacyClient.ts, packages/api/src/client/__tests__/DedotClient.spec.ts, packages/api/src/client/__tests__/LegacyClient.spec.ts, packages/api/src/types.ts
=> feat: emit `runtimeUpgraded` event

packages/api/src/client/__tests__/DedotClient.spec.ts, packages/api/src/extrinsic/submittable/SubmittableExtrinsic.ts, packages/api/src/extrinsic/submittable/SubmittableExtrinsicV2.ts, packages/api/src/extrinsic/submittable/utils.ts, packages/types/src/extrinsic.ts, zombienet-tests/src/0001-check-tx-batch-v2.ts, zombienet-tests/src/0001-check-tx-transfer-balance-v2.ts, zombienet-tests/src/0001-check-tx-transfer-balance.ts
Adding `blockNumber` to status: `BestChainBlockIncluded` & `Finalized`.
=> feat(api): add block number to TxStatus

README.md, packages/contracts/src/executor/ConstructorQueryExecutor.ts, packages/contracts/src/executor/ConstructorTxExecutor.ts, packages/contracts/src/types/index.ts, zombienet-tests/src/0001-verify-contract-errors.ts
=> fix(contract): make `salt` optional

packages/cli/package.json, packages/cli/src/commands/chaintypes.ts, packages/cli/src/commands/typink.ts, packages/codegen/src/chaintypes/generator/IndexGen.ts, packages/codegen/src/chaintypes/index.ts, packages/codegen/src/chaintypes/templates/index.hbs, packages/codegen/src/index.ts, packages/codegen/src/types.ts, packages/codegen/src/typink/generator/IndexGen.ts, packages/codegen/src/typink/index.ts, packages/codegen/src/typink/templates/index.hbs, yarn.lock
This PR addresses a task in #177 which adds the following features:
-  Text generation while performing tasks.
-  Spinner & icons to indicate ongoing, success, and error process.
This also fix a few issues with `-c` option to customize chain name / contract name.
=> fix(cli): improve text clarity, add spinner and icons

packages/cli/bin/dedot.mjs, packages/cli/package.json, packages/cli/tsconfig.build.json, packages/codegen/src/utils.ts, scripts/copy-files-to-dist.js
=> fix(cli): cjs issue with ora

packages/codecs/src/codecs/generic/AccountId32.ts, packages/codecs/src/codecs/generic/__tests__/AccountId32.spec.ts, packages/contracts/src/Contract.ts, packages/contracts/src/TypinkRegistry.ts, packages/contracts/src/__tests__/Contract.spec.ts, packages/contracts/src/executor/EventExecutor.ts
Contract are now trying decode events from other contract instance using the same code as well, this will fix the issue.
=> fix(contracts): decode events for specific contract address

packages/api/src/extrinsic/extensions/known/CheckMortality.ts
Closes: https://github.com/dedotdev/dedot/issues/60
=> fix: support aura slot duration when calculating mortality

packages/api/package.json, packages/api/src/client/BaseSubstrateClient.ts, packages/api/src/client/__tests__/DedotClient.spec.ts, packages/api/src/extrinsic/extensions/ExtraSignedExtension.ts, packages/api/src/extrinsic/extensions/SignedExtension.ts, packages/api/src/extrinsic/extensions/known/ChargeAssetTxPayment.ts, packages/api/src/extrinsic/extensions/known/ChargeTransactionPayment.ts, packages/api/src/extrinsic/extensions/known/CheckGenesis.ts, packages/api/src/extrinsic/extensions/known/CheckMetadataHash.ts, packages/api/src/extrinsic/extensions/known/CheckMortality.ts, packages/api/src/extrinsic/extensions/known/CheckNonce.ts, packages/api/src/extrinsic/extensions/known/CheckSpecVersion.ts, packages/api/src/extrinsic/extensions/known/CheckTxVersion.ts, packages/api/src/extrinsic/submittable/BaseSubmittableExtrinsic.ts, packages/api/src/extrinsic/submittable/fakeSigner.ts, packages/api/src/extrinsic/submittable/utils.ts, packages/api/src/types.ts, packages/types/src/extrinsic.ts, packages/types/src/index.ts, packages/types/src/pjs-types.ts, yarn.lock, zombienet-tests/package.json, zombienet-tests/src/0001-check-tx-alter-payload.ts
=> refactor: remove @polkadot/types

package.json, packages/api/src/executor/StorageQueryExecutor.ts, packages/api/src/executor/v2/StorageQueryExecutorV2.ts, packages/api/src/storage/QueryableStorage.ts, packages/types/src/generic.ts, yarn.lock, zombienet-tests/src/0001-check-query-with-partial-keys.ts, zombienet-tests/src/0001-small-network.zndsl
=> feat: support partial key/input query for double, nth-map storage

packages/api/src/client/BaseSubstrateClient.ts, packages/api/src/client/__tests__/BaseSubstrateClient.spec.ts
=> fix: failsafe for metadata caching

packages/codegen/src/typink/generator/TypesGen.ts, packages/contracts/src/__tests__/utils.spec.ts, packages/contracts/src/types/shared.ts, packages/contracts/src/utils.ts
Changes:
- Add handle for all possible types when normalizing contract types.
- Fix recursive errors when types depend on each other.
=> fix(codegen/tyink): add missing types and handle recursive errors

README.md, packages/api/src/client/BaseSubstrateClient.ts, packages/api/src/client/DedotClient.ts, packages/api/src/client/LegacyClient.ts, packages/api/src/client/__tests__/DedotClient.spec.ts, packages/api/src/extrinsic/submittable/SubmittableExtrinsicV2.ts, packages/api/src/storage/NewStorageQuery.ts, packages/api/src/storage/__tests__/NewStorageQuery.spec.ts, packages/api/src/types.ts, packages/providers/src/ws/WsProvider.ts, zombienet-tests/src/0001-check-storage-subscription-reconnection.ts, zombienet-tests/src/0001-small-network.zndsl, zombienet-tests/src/0001-verify-dedot-client-events.ts
Fix issue storage subscriptions via DedotClient stop emitting changes after auto-reconnecting.
=> fix(clients): subscriptions should work after auto-reconnect

packages/api/src/json-rpc/group/ChainHead/ChainHead.ts, packages/types/src/generic.ts
Many thanks to @danebulat for reporting the issue 🙏
=> fix(api): fetching storage entries via smoldot

packages/api/src/json-rpc/group/ChainHead/ChainHead.ts
Kudo to @danebulat for reporting the issue 🙏
=> fix(api): fetching empty storage items via smoldot

packages/codecs/src/registry/TypeRegistry.ts
=> fix: optional bool codec

packages/codegen/package.json, packages/codegen/src/sol/generator/ConstructorQueryGen.ts, packages/codegen/src/sol/generator/ConstructorTxGen.ts, packages/codegen/src/sol/generator/EventsGen.ts, packages/codegen/src/sol/generator/QueryGen.ts, packages/codegen/src/sol/generator/TxGen.ts, packages/codegen/src/sol/generator/TypesGen.ts, packages/contracts/src/Contract.ts, packages/contracts/src/ContractDeployer.ts, packages/contracts/src/types/index.ts
Add LooseSolAbi, clear typgen cache & copy templates etc...
=> fix: misc contracts fixes
