dedotdev/dedot

- packages/api/package.json
- packages/api/src/client/Dedot.ts
- packages/api/src/types.ts
- packages/api/tsconfig.build.cjs.json
- packages/api/tsconfig.build.json
- packages/api/tsconfig.json
- packages/storage/LICENSE
- packages/storage/README.md
- packages/storage/package.json
- packages/storage/src/IStorage.ts
- packages/storage/src/impl/LocalStorage.ts
- packages/storage/src/impl/index.ts
- packages/storage/src/index.ts
- packages/storage/tsconfig.build.cjs.json
- packages/storage/tsconfig.build.json
- packages/storage/tsconfig.json
- tsconfig.base.json
- yarn.lock
This PR addresses #44 
We're now using localStorage as a default caching Storage, removing the tight coupling `localForage`, we also add a `IStorage` interface, so other means of caching can be implemented later as needed.
> Decouple metadata caching storage to a @dedot/storage

- package.json
- packages/api/src/chaintypes/substrate/json-rpc.ts
- packages/api/src/chaintypes/substrate/query.ts
- packages/api/src/executor/Executor.ts
- packages/api/src/executor/StorageQueryExecutor.ts
- packages/api/src/storage/QueryableStorage.ts
- packages/cli/src/commands/chaintypes.ts
- packages/codegen/src/generator/QueryGen.ts
- packages/shape/src/lean/Enum.ts
- packages/types/src/index.ts
- zombienet-tests/src/0001-check-storage-query.ts
This add more utility method for storage map:
- `.keys`: list all decoded keys of a storage map with pagination support
- `.entries`: list all decoded entries of a storage map with pagination support
> feat: improve storage query

- packages/api/src/executor/StorageQueryExecutor.ts
As title, this happens because the storage subscription only notify the changed storage values.
> fix: mismatch order of query subscription changes

- packages/api/src/index.ts
- packages/api/src/storage/index.ts
- scripts/copy-files-to-dist.js
Changes:
- Expose `QueryableStorage` type
- Expose default/generic substrate chaintypes under `dedot/chaintypes` instead of the root `dedot` namespace.
> feat(api): update api exposure

- packages/api/src/client/__tests__/Dedot.spec.ts
- packages/api/src/client/__tests__/MockProvider.ts
- packages/api/src/executor/StorageQueryExecutor.ts
We're using `state_queryStorageAt` instead of `state_getStorage` for storage query to optimize multi query.
> tweak(api): improve multi storage query

- packages/api/src/client/__tests__/MockProvider.ts
- packages/api/src/json-rpc/group/ChainSpec.ts
- packages/api/src/json-rpc/group/JsonRpcGroup.ts
- packages/api/src/json-rpc/group/Transaction.ts
- packages/api/src/json-rpc/group/TransactionWatch.ts
- packages/api/src/json-rpc/group/__tests__/ChainSpec.spec.ts
- packages/api/src/json-rpc/group/__tests__/JsonRpcGroup.spec.ts
- packages/api/src/json-rpc/group/index.ts
- packages/api/src/json-rpc/index.ts
- packages/api/src/types.ts
- packages/utils/src/deferred.ts
- packages/utils/src/index.ts
- packages/utils/src/misc.ts
- zombienet-tests/src/0001-small-network.zndsl
- zombienet-tests/src/0001-tx-broadcaster.ts
We're adding a `JsonRpcGroup` abstraction to help dealing with multi-version supported nature of the [new json rpc spec](https://paritytech.github.io/json-rpc-interface-spec/grouping-functions-and-node-capabilities.html).
The `JsonRpcGroup` help us:
- Detect the supported version a spefic prefixed json-rpc group
- Send a json-rpc method in the group without having to specify the prefix & version.
On top of this we're adding a new high-level abstraction for existing json-rpc group like: ChainSpec, Transaction & TransactionWatch
> feat(api): json rpc groups

- packages/api/src/client/BaseSubstrateClient.ts
- packages/api/src/client/Dedot.ts
- packages/api/src/client/DedotClient.ts
- packages/api/src/client/__tests__/Dedot.spec.ts
- packages/api/src/client/__tests__/DedotClient.spec.ts
- packages/api/src/index.ts
- packages/api/src/json-rpc/JsonRpcClient.ts
- packages/api/src/json-rpc/group/ChainHead/ChainHead.ts
- packages/api/src/types.ts
- packages/codegen/src/index.ts
- packages/providers/src/ws/WsProvider.ts
- zombienet-tests/src/0001-check-runtime-api.ts
- zombienet-tests/src/0001-check-storage-query-v2.ts
- zombienet-tests/src/0001-check-storage-query.ts
- zombienet-tests/src/0001-check-tx-batch-v2.ts
- zombienet-tests/src/0001-check-tx-batch.ts
- zombienet-tests/src/0001-check-tx-transfer-balance-v2.ts
- zombienet-tests/src/0001-check-tx-transfer-balance.ts
- zombienet-tests/src/0001-tx-broadcaster.ts
- zombienet-tests/src/0001-verify-chain-head-logic.ts
This is a breaking change.
Rationale:
- Previously, `WsProvider` were tight coupled inside the JsonRpcClient which makes it more convenient when initialize the client by only feeding the endpoint url, e.g: `JsonRpcClient.new('wss://rpc.polkadot.io')`
- Now, we're having `SmoldotProvider`, so users might choose between 2 options. If `SmoldotProvder` is used, `WsProvider` should not be included inside the bundle and vise-versa via the tree-shaking process.
- TODO update docs & comments.
> tweak!: remove `WsProvider` tight coupling

- packages/api/src/json-rpc/group/ChainHead/ChainHead.ts
- packages/api/src/json-rpc/group/__tests__/ChainHead.spec.ts
Caching supported for responses from these requests/operations:
- `chainHead_header`
- `chainHead_body`
- `chainHead_call`
- `chainHead_storage`
> feat(api): chainHead responses caching

- package.json
- packages/api/package.json
- packages/api/src/extrinsic/extensions/known/CheckMetadataHash.ts
- packages/api/src/extrinsic/extensions/known/index.ts
- packages/cli/package.json
- packages/types/src/extrinsic.ts
- yarn.lock
Ref: https://github.com/paritytech/polkadot-sdk/pull/4619
TODO: Upgrade zombienet versioning to one that support CheckMetadataHash extension
> feat: add CheckMetadatHash extension

- README.md
- examples/dapp/src/App.tsx
- packages/api/src/client/LegacyClient.ts
- packages/api/src/client/__tests__/LegacyClient.spec.ts
- packages/api/src/client/index.ts
- packages/codegen/src/index.ts
- packages/contracts/src/__tests__/Contract.spec.ts
- packages/contracts/src/__tests__/ContractDeployer.spec.ts
- zombienet-tests/src/0001-check-contract-api.ts
- zombienet-tests/src/0001-check-payment-info.ts
- zombienet-tests/src/0001-check-runtime-api.ts
- zombienet-tests/src/0001-check-storage-map-pagination.ts
- zombienet-tests/src/0001-check-storage-query.ts
- zombienet-tests/src/0001-check-tx-batch.ts
- zombienet-tests/src/0001-check-tx-transfer-balance.ts
- zombienet-tests/src/0001-tx-broadcaster.ts
Rename the legacy client from `Dedot` to `LegacyClient`.
The new client `DedotClient` built on top of the new JsonRpc is recommended to use. Users can also still use the `LegacyClient` as well if the JSON RPC server does not support new spec.
> fix!: rename legacy client

- .github/workflows/zombienet-tests.yml
- README.md
New zombienet executable versions causing some inconsistency in executing e2e tests, for now let's revert it back to the previous version. We'll investigate the root cause of the inconsistency and going back later.
> chore: revert zombienet versions

- packages/api/src/chaintypes/substrate/tx.ts
- packages/api/src/extrinsic/submittable/SubmittableExtrinsic.ts
- packages/api/src/extrinsic/submittable/SubmittableExtrinsicV2.ts
- packages/api/src/extrinsic/submittable/utils.ts
- packages/codegen/src/chaintypes/generator/TxGen.ts
- packages/types/src/extrinsic.ts
I find it a bit weird using the name `TransactionEvent` while we still using the field `status` in `ISubmittableResult` for this type. So I decided to go with `TxStatus` since `TransactionStatus` are already exist to prevent people confusing if there're 2 types with the same name or so.
> breaking: TransactionEvent -> TxStatus

- packages/api/src/chaintypes/substrate/tx.ts
- packages/api/src/extrinsic/submittable/SubmittableExtrinsicV2.ts
- packages/api/src/extrinsic/submittable/SubmittableResult.ts
- packages/codegen/src/chaintypes/generator/TxGen.ts
- packages/codegen/src/typink/generator/EventsGen.ts
- packages/types/src/extrinsic.ts
Follow up on #184 & #185
Since we're using the same interface for transaction status, it's make sense to remove the generic over TxStatus now.
> fix: remove generic over TxStatus

- packages/api/src/client/BaseSubstrateClient.ts
- packages/api/src/client/DedotClient.ts
- packages/api/src/client/LegacyClient.ts
- packages/api/src/client/__tests__/DedotClient.spec.ts
- packages/api/src/client/__tests__/LegacyClient.spec.ts
- packages/api/src/types.ts
Closes #196
This new async version of `getRuntimeVersion` will ensure that the runtime upgrade process is done (download metadata, setup registry, caching ...) before returning the value. Helpful when we want to prepare for runtime upgrades.
So the process of preparing for new runtime upgrades would look like this:
```typescript
const client = await DedotClient<OldApi>.new(...)
const runtimeVersion = await client.getRuntimeVersion();
if (runtimeVersion.specVersion === NEW_SPEC_VERSION) {
// casting the client to using the NewApi interface, generated from the new metadata
const newClient: DedotClient<NewApi> = api as any; 
newClient.tx.pallet.new_tx_call(...)
} else {
client.tx.pallet.old_tx_call(...)
}
```
Pending some specs to verify the logics
> feat(api): add `getRuntimeVersion` to clients

- packages/contracts/src/types/shared.ts
- packages/contracts/src/utils.ts
The `fields` prop in `composite` type can also be missing in  contract metadata as well, this will fix the case.
> fix(contracts): missing fields for composite type

- packages/api/src/client/BaseSubstrateClient.ts
- packages/api/src/client/__tests__/DedotClient.spec.ts
- packages/api/src/extrinsic/submittable/BaseSubmittableExtrinsic.ts
- packages/api/src/types.ts
- zombienet-tests/src/0001-check-tx-alter-payload.ts
Add a global option to setup signer instance to the client via ApiOptions, so we don't have to specify the `signer` everytime submitting a transaction.
> feat(client): add signer to ApiOptions

- packages/codegen/src/typink/index.ts
- packages/utils/src/string/__tests__/cases.spec.ts
- packages/utils/src/string/cases.ts
This PR changes the way `typink` handles contract metadata names contain whitespace. 
Previously: Directory names included whitespace (picture below). 
Now: Directory names are converted to hyphen-separated and lowercase (e.g., "flipper-contract").
> fix(codegen): typink folder name contains space

- packages/cli/src/dedot.ts
`dedot -v` is now showing the current version of the working project, not the version of the cli. For now, let's disable it.
> fix(cli): disable cli version cmd

- packages/api/src/executor/Executor.ts
- packages/api/src/executor/RuntimeApiExecutor.ts
- packages/api/src/executor/StorageQueryExecutor.ts
- packages/api/src/executor/TxExecutor.ts
- packages/api/src/executor/v2/RuntimeApiExecutorV2.ts
- packages/api/src/executor/v2/StorageQueryExecutorV2.ts
- packages/api/src/executor/v2/TxExecutorV2.ts
- packages/api/src/extrinsic/extensions/ExtraSignedExtension.ts
- packages/api/src/extrinsic/extensions/SignedExtension.ts
- packages/api/src/extrinsic/extensions/known/CheckGenesis.ts
- packages/api/src/extrinsic/extensions/known/CheckMortality.ts
- packages/api/src/extrinsic/extensions/known/CheckNonce.ts
- packages/api/src/extrinsic/extensions/known/CheckSpecVersion.ts
- packages/api/src/extrinsic/extensions/known/CheckTxVersion.ts
- packages/api/src/extrinsic/submittable/BaseSubmittableExtrinsic.ts
- packages/api/src/extrinsic/submittable/SubmittableExtrinsic.ts
- packages/api/src/extrinsic/submittable/SubmittableExtrinsicV2.ts
- packages/codegen/src/typink/templates/index.hbs
- packages/contracts/src/Contract.ts
- packages/contracts/src/ContractDeployer.ts
- packages/contracts/src/executor/ConstructorQueryExecutor.ts
- packages/contracts/src/executor/ConstructorTxExecutor.ts
- packages/contracts/src/executor/Executor.ts
- packages/contracts/src/executor/QueryExecutor.ts
- packages/contracts/src/executor/TxExecutor.ts
- packages/contracts/src/utils.ts
- zombienet-tests/src/contracts/flipper/index.d.ts
This also comes with:
- Renaming client variable for consistency in code base, this will change the exposed client in some internal primitives, so I'll mark this PR as breaking, but this does not break high-level API.
- Fix a minor RpcVersion selection issue with generated ContractApi interface
> breaking: expose SubstrateClient for Contract & ContractDeployer

- package.json
- packages/api/package.json
- packages/cli/package.json
- yarn.lock
- zombienet-tests/package.json
There is an issue with @polkadot/types-support >= v14.1.1, we'll keep the version at 14.0.1 for now.
> chore: bump @polkadot/types-support

- packages/api/src/json-rpc/group/ChainHead/ChainHead.ts
- zombienet-tests/src/0001-check-query-multi.ts
Fix inconsistent type of returned apis, in some network endpoints (e.g: `wss://rpc-westend.luckyfriday.io`)  the `runtimeVersion.apis` is an array instead of a map/object (maybe using an old version of the sdk). Here we convert it to a map format for consistency.
> fix: inconsistent apis format from runtime version

- packages/api/src/json-rpc/group/ChainHead/ChainHead.ts
- packages/api/src/storage/NewStorageQuery.ts
Fix a critical performance issue with smoldot where `.queryMulti` performs worse if we send multiple keys at once via chainHead.storage API. This might potentially related to caching issue on smoldot side.
For now:
- Smoldot: Send each key one by one
- WebSocket: Send all keys at once.
> fix: optimize smoldot performance for `.queryMulti`

- packages/api/src/client/__tests__/DedotClient.spec.ts
- packages/api/src/json-rpc/group/ChainHead/ChainHead.ts
- packages/api/src/json-rpc/group/__tests__/ChainHead.spec.ts
- packages/api/src/storage/NewStorageQuery.ts
Currently, we're trying to unpin all obsolete blocks at the same hight with finalized blocks on `finalized` event without checking its usage, this might potentially causing issue if there is a long running operation on these obsolete block hashes.
This case is a bit complicated to reproduce and might happen once in a while if forks happen.
Big thanks to @danebulat for reporting this error & behavior.
> fix(chainHead): unpin strategy improvements, clean up long pulling queue

- packages/api/src/json-rpc/group/ChainHead/ChainHead.ts
- packages/utils/src/queue/ThrottleQueue.ts
- packages/utils/src/queue/__tests__/ThrottleQueue.spec.ts
- packages/utils/src/queue/index.ts
In big/complicated dapps (Polkadot Staking Dashboard or Polkadot Live), the number of operations sending to JSON-RPC server might be a lot at a time, this accidentally putting too much stress on the JSON-RPC server, especially smoldot/light-client causing it to hangup and not respond at all.
This PR introduce a `ThrottleQueue` to help ease up this issue, this will make sure there will be a certain number of concureny requests/operations can be send at a time and new requests/operations will be put in the queue waiting to be executed in line.
> perf: add throttle queue

- packages/api/src/extrinsic/extensions/ExtraSignedExtension.ts
- packages/api/src/extrinsic/submittable/BaseSubmittableExtrinsic.ts
- zombienet-tests/src/0001-check-tx-alter-payload.ts
Dedot does support signer/wallet to alter transaction with #190
But with [this change](https://github.com/polkadot-js/api/pull/5920) from PJS, wallet/signer now expect a `withSignedTransaction: true` in the payload to enable altering transaction. This PR is to:
1. Send `withSignedTransaction: true` by default to signer to allow altering transaction.
2. We also allow signer/wallet to alter call data.
> fix: send `withSignedTransaction:true` by default and allow alter tx call data

- packages/providers/src/__tests__/utils.spec.ts
- packages/providers/src/utils.ts
- packages/providers/src/ws/WsProvider.ts
- packages/providers/src/ws/__tests__/WsProvider.spec.ts
Enhanced `WsProvider` to accept an array of WebSocket endpoints for automatic failover. Endpoints are randomly selected on initial connection, and reconnection attempts exclude previously failed endpoints when possible.
```typescript
// Single endpoint
const provider = new WsProvider('wss://rpc.polkadot.io');
// Multiple endpoints for failover
const provider = new WsProvider([
'wss://rpc.polkadot.io',
'wss://polkadot-rpc.dwellir.com',
'wss://polkadot.api.onfinality.io/public-ws'
]);
```
This new feature leverages the endpointSelector we had previously in #462
> feat(providers): WsProvider to support list of endpoints

- examples/scripts/multiple-endpoints.ts
- packages/api/src/client/DedotClient.ts
- packages/api/src/json-rpc/JsonRpcClient.ts
- packages/providers/src/base/SubscriptionProvider.ts
- packages/providers/src/ws/WsProvider.ts
- packages/providers/src/ws/__tests__/WsProvider.spec.ts
Emit current connected endpoint on `WsProvider` connected event.
```ts
const provider = new WsProvider([
'wss://rpc.polkadot.io',
'wss://polkadot-rpc.dwellir.com',
'wss://polkadot.api.onfinality.io/public-ws',
]);
provider.on('connected', (connectedUrl) => {
console.log('Connected Endpoint:', connectedUrl);
});
await provider.connect();
```
> feat: emit current endpoint on WsProvider connected

- packages/providers/src/error.ts
- packages/providers/src/ws/WsProvider.ts
- zombienet-tests/src/0001-small-network-batch-01.zndsl
- zombienet-tests/src/0001-ws-provider-max-retry-attempts.ts
This PR introduces a `maxRetryAttempts` option to WsProvider, once the retry attempts reach this number it will give up  and emit an error `MaxRetryAttemptedError`.
```ts
const provider = new WsProvider({
endpoint: 'ws://127.0.0.1:9944',
maxRetryAttempts: 3,
retryDelayMs: 3000
});
// This will throw MaxRetryAttemptedError after 3 retries if the endpoint is unreachable.
await provider.connect(); 
```
cc: @S2kael
> feat(providers): add max retry attempts option

- examples/scripts/keyring.ts
- examples/scripts/merkleized-metadata.ts
- examples/scripts/sign-from-json-payload.ts
- packages/api/src/extrinsic/extensions/ExtraSignedExtension.ts
- packages/api/src/extrinsic/extensions/FallbackSignedExtension.ts
- packages/api/src/extrinsic/extensions/SignedExtension.ts
- packages/api/src/extrinsic/extensions/known/ChargeAssetTxPayment.ts
- packages/api/src/extrinsic/extensions/known/ChargeTransactionPayment.ts
- packages/api/src/extrinsic/extensions/known/CheckGenesis.ts
- packages/api/src/extrinsic/extensions/known/CheckMetadataHash.ts
- packages/api/src/extrinsic/extensions/known/CheckMortality.ts
- packages/api/src/extrinsic/extensions/known/CheckNonce.ts
- packages/api/src/extrinsic/extensions/known/CheckSpecVersion.ts
- packages/api/src/extrinsic/extensions/known/CheckTxVersion.ts
- packages/api/src/extrinsic/submittable/BaseSubmittableExtrinsic.ts
- packages/api/src/extrinsic/submittable/index.ts
- packages/api/src/extrinsic/submittable/utils.ts
- packages/utils/src/__tests__/hex.spec.ts
- packages/utils/src/hex.ts
Add a helper into the `ExtraSignedExtension` to allow convert json payload to raw payload for siging purposes.
```ts
import { DedotClient, ExtraSignedExtension, signRawMessage, WsProvider } from 'dedot';
import { SignerPayloadJSON, SignerResult } from 'dedot/types';
import { u8aToHex } from 'dedot/utils';
const payload: SignerPayloadJSON = { ... };
const extra = new ExtraSignedExtension(client, { signerAddress: payload.address });
await extra.fromPayload(payload);
const rawPayload = extra.toRawPayload(payload.method as HexString).data;
const signature = u8aToHex(signRawMessage(alice, rawPayload));
```
> feat: helper to sign from json payload

- e2e/contracts/src/tests/errors.test.ts
- packages/codecs/src/registry/__tests__/PortableRegistry.spec.ts
- packages/contracts/src/__tests__/errors.spec.ts
- packages/contracts/src/errors.ts
- packages/contracts/src/executor/ConstructorQueryExecutor.ts
- packages/contracts/src/executor/QueryExecutor.ts
Expose the detailed module error for contract's dispatch errors. Devs now don't have to manually call `client.registry.findErrorMeta` every time hitting a dispatch error.
> feat(contracts): expose module errors

- e2e/contracts/src/tests/DedotClientAt.test.ts
- e2e/contracts/src/tests/LegacyClientAt.test.ts
- packages/api/src/client/BaseSubstrateClient.ts
- packages/api/src/client/DedotClient.ts
- packages/api/src/client/LegacyClient.ts
- packages/api/src/client/__tests__/DedotClient.spec.ts
- packages/api/src/client/__tests__/LegacyClient.spec.ts
- packages/api/src/types.ts
`.queryMulti` now availalable on `ISubstrateClientAt` instances.
```ts
const clientAt = await client.at('0x...');
// Fully-typed data
const [aliceAccount, blockNumber, parentHash, bobAccount] = await clientAt.queryMulti([
{ fn: clientAt.query.system.account, args: [ALICE] },
{ fn: clientAt.query.system.number, args: [] },
{ fn: clientAt.query.system.parentHash, args: [] },
{ fn: clientAt.query.system.account, args: [BOB] },
]);
```
> feat(api): support `queryMulti` for client.at instances
